name: "Discord Notification"


on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master
      - dev

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: GEF Push Notification
        if: github.event_name == 'push' && github.repository_owner == 'hugsy'
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: "[${{ github.repository }}] ${{ github.actor }} pushed to `${{ github.ref }}`"
          description: |
            **Commits**:
              ● ${{ join(github.event.commits.*.message, '
              ● ') }}
            ---
            **Link**: ${{ github.event.compare }}

          color: 0x0000ff
          username: ${{ github.actor }} via GithubBot
          avatar_url: ${{ github.actor.avatar_url }}

      - name: GEF Pull Request Notification
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: "[${{ github.repository }}] ${{ github.actor }} created a new Pull Request (`#${{ github.event.pull_request.number }}`)"
          description: |
            **${{ github.event.pull_request.title }}**

            ---
            **Link**: ${{ github.event.pull_request.html_url }}
          color: 0x00ff00
          username: ${{ github.actor }} via GithubBot
          avatar_url: ${{ github.actor.avatar_url }}

      - name: GEF Issue Notification
        if: github.event_name == 'issues' && github.event.action == 'opened' && github.repository_owner == 'hugsy'
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: "[${{ github.repository }}] ${{ github.actor }} created a new Issue (`#${{ github.event.issue.number }}`)"
          description: |
            **${{ github.event.issue.title }}**

            ---
            **Link**: ${{ github.event.issue.html_url }}
          color: 0xff0000
          username: ${{ github.actor }} via GithubBot
          avatar_url: ${{ github.actor.avatar_url }}
