# https://developer.github.com/v3/activity/events/types/
name: "IRC Notification"
on: [push, pull_request, issues]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push'
        with:
          channel: "##gef"
          nickname: githubot
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message) }}
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          channel: "##gef"
          nickname: githubot
          message: |
            ${{ github.actor }} ${{ github.event.action }} PR #${{ github.event.pull_request.number }}: "${{ github.event.pull_request.title }}" (${{ github.event.pull_request.url }})
      - name: irc issue
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'issues' && github.event.action == 'opened'
        with:
          channel: "##gef"
          nickname: githubot
          message: |
            ${{ github.actor }} ${{ github.event.action }} issue #number: "${{ github.event.issue.title }}" (${{ github.event.issue.html_url }})
